# Override default values in 'scripts/default_config.py'

data:
  sources: ['market1501']
  targets: ['market1501']
  height: 384
  width: 128
  norm_mean: [0.5, 0.5, 0.5]
  norm_std: [0.5, 0.5, 0.5]
  transforms: ["rc", "re", "bipo"]
  aug_ratio: 0.2
  bipo:
    p: 0.2

sampler:
  train_sampler: RandomIdentitySampler

model:
  name: 'kpr'
  kpr:
    backbone: "solider_swin_base_patch4_window7_224"
    keypoints:
      prompt_masks: keypoints_gaussian
      prompt_preprocess: cck6
    masks:
      dir: "pifpaf_maskrcnn_filtering"
      preprocess: "five_v"
  transreid:
    cam_num: 6
  text_prompt:
    enabled: True
    train_json_path: "/scratch/ghtmd9277/keypoint_promptable_reidentification/Market-1501-v15.09.15/market1501_train_caption.json"
    query_json_path: "/scratch/ghtmd9277/keypoint_promptable_reidentification/Market-1501-v15.09.15/market1501_query_caption.json"
    clip_model_name: "ViT-B/32"
    fusion_layer: 0
    feature_dim_match: True
    text_dim: 512

train:
  lr: 0.0002
  reduced_lr: 0.0002
  fixbase_epoch: 20
  # warmup_t: 10
  batch_size : 64
  accumulation_steps : 1
  max_epoch : 150

loss:
  triplet: 
    margin: 0.5
    weight_t: 7.0
    weight_x: 3.0
