data:
  sources: ['market1501']
  targets: ['market1501']
  height: 384
  width: 128
  norm_mean: [0.485, 0.456, 0.406]
  norm_std: [0.229, 0.224, 0.225]
  aug_ratio: 0.0
  bipo:
    p: 0.05

model:
  kpr:
    backbone: swin_base_patch4_window7_224.ms_in22k_ft_in1k
    keypoints:
      prompt_masks: keypoints_gaussian
      prompt_preprocess: cck6
    masks:
      dir: "pifpaf_maskrcnn_filtering"
      preprocess: "five_v"
  transreid:
    cam_num: 6
  text_prompt:
    enabled: True
    train_json_path: "./Market-1501-v15.09.15/market1501_train_caption.json"
    query_json_path: "./Market-1501-v15.09.15/person_descriptions_query.json"
    clip_model_name: "ViT-B/32"
    fusion_layer: 0
    feature_dim_match: True
train:
  warmup_t: 10
  batch_size: 32
  max_epoch: 150
  accumulation_steps : 1
loss:
  triplet: 
    margin: 0.5
    weight_t: 0.3
    weight_x: 0.7
  supercon:
    enabled: True
    temperature: 0.07
    weight: 0.5 