data:
  # sources: ['market1501_aug']
  sources: ['market1501']
  targets: ['market1501']
  height: 384
  width: 128
  norm_mean: [0.485, 0.456, 0.406]
  norm_std: [0.229, 0.224, 0.225]
  aug_ratio : 0.1
  
  bipo:
    p: 0.05
sampler:
  train_sampler : RandomIdentitySampler

model:
  kpr:
    backbone: swin_base_patch4_window7_224.ms_in22k_ft_in1k
    keypoints:
      prompt_masks: keypoints_gaussian
      prompt_preprocess: cck6
    masks:
      dir: "pifpaf_maskrcnn_filtering"
      preprocess: "five_v"
  transreid:
    cam_num: 6
  text_prompt:
    enabled: True
    train_json_path: "/home/hseung/keypoint_promptable_reidentification/Market-1501-v15.09.15/market1501_train_caption.json"
    query_json_path: "/home/hseung/keypoint_promptable_reidentification/Market-1501-v15.09.15/person_descriptions_query.json"
    clip_model_name: "ViT-B/32"
    fusion_layer: 0
    feature_dim_match: True
train:
  warmup_t: 15
  batch_size : 64
  # fixbase_epoch: 10 
  max_epoch : 200
  accumulation_steps : 1
loss:
  part_based:
    weights:
      globl:
        id: 1.0       # 원래 값 유지
        tr: 0.0       # 추가 (전체 체형 학습)
  #     foreg:
  #       id: 1.0       # 원래 값 유지
  #       tr: 0.4       # 추가 (전경 영역 학습)
  #     conct:
  #       id: 1.0       # 원래 값 유지
  #       tr: 0.6       # 추가 (통합 파트 학습)
  #     parts:
  #       id: 0.0       # 원래 값 유지
  #       tr: 0.8       # 감소 (1.0 → 0.7, 과적합 완화)
  triplet: 
    margin : 0.5
  supercon:
    enabled: True
    temperature: 0.07
    weight: 1.0       # 원래 값 유지
    mode: "global"      # 유지
    weight_global: 1.0  # 증가 (체형/실루엣 강화)
    weight_concat: 0.0  # 감소 (파트 의존도 감소)
    norm_type: 2.0
    hard_mining: False
    hard_mining_ratio: 0.5