# Override default values in 'scripts/default_config.py'

data:
  sources: ['occ_PoseTrack21']
  targets: ['occ_PoseTrack21']
  height: 256
  width: 128
  norm_mean: [0.485, 0.456, 0.406]
  norm_std: [0.229, 0.224, 0.225]
  bipo:
    masks_dir: pose_on_img_crops

model:
  kpr:
    keypoints:
      prompt_masks: keypoints_gaussian
      prompt_preprocess: cck8
    masks:
      dir: "pose_on_img_crops"
      preprocess: "eight"
  transreid:
    sie_camera: False
